In [1]:
import torch

In [27]:
def binary_code_entropy_loss(predcition,target):
    epsilon=1e-8
    predcition=torch.clamp(predcition,epsilon,1-epsilon)
    return -(target*torch.log(predcition)+(1-target)*torch.log(1-predcition))

In [2]:
x=torch.tensor(3.0,requires_grad=True)

In [3]:
y=x**2

In [4]:
x

tensor(3., requires_grad=True)

In [5]:
y

tensor(9., grad_fn=<PowBackward0>)

In [6]:
y.backward()

In [7]:
y

tensor(9., grad_fn=<PowBackward0>)

In [9]:
x.grad

tensor(6.)

In [10]:
x=torch.tensor(3.0,requires_grad=True)

In [11]:
y=x**2

In [12]:
z=torch.sin(y)

In [13]:
x

tensor(3., requires_grad=True)

In [14]:
y

tensor(9., grad_fn=<PowBackward0>)

In [15]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [16]:
z.backward()

In [17]:
x.grad

tensor(-5.4668)

autograde example

In [30]:
x=torch.tensor(6.7)

In [31]:
y=torch.tensor(0.0)

In [32]:
w=torch.tensor(1.1,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [33]:
w

tensor(1.1000, requires_grad=True)

In [34]:
b

tensor(0., requires_grad=True)

In [36]:
z=w*x+b

In [37]:
y_pred=torch.sigmoid(z)

In [38]:
y_pred

tensor(0.9994, grad_fn=<SigmoidBackward0>)

In [39]:
loss=binary_code_entropy_loss(y_pred,y)

In [40]:
loss

tensor(7.3706, grad_fn=<NegBackward0>)

In [41]:
loss.backward()

In [42]:
w.grad

tensor(6.6958)

In [43]:
b.grad

tensor(0.9994)

another example for autograde 

In [78]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)


In [94]:
y=(x**2).mean()

In [95]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [96]:
y.backward()

In [97]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

clearing grad

In [98]:
x.grad.zero_()

tensor([0., 0., 0.])

to remove the gradient track

In [99]:
z=x.detach()

In [100]:
z

tensor([1., 2., 3.])

In [101]:
x

tensor([1., 2., 3.], requires_grad=True)

In [103]:
x.requires_grad_(False)

tensor([1., 2., 3.])