In [242]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch.nn as nn 
import torch


In [243]:
df=pd.read_csv(r'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [244]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [246]:
df.shape

(569, 33)

In [247]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [248]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [249]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [250]:
print(df.iloc[:, 1:])

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  sym

In [251]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [252]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [253]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
211       11.840         18.94           75.51      428.0          0.08871   
349       11.950         14.96           77.23      426.7          0.11580   
302       20.090         23.86          134.70     1247.0          0.10800   
555       10.290         27.61           65.67      321.4          0.09030   
525        8.571         13.10           54.53      221.3          0.10360   
..           ...           ...             ...        ...              ...   
15        14.540         27.54           96.73      658.8          0.11390   
347       14.760         14.74           94.87      668.7          0.08875   
164       23.270         22.04          152.10     1686.0          0.08439   
374       13.690         16.07           87.84      579.1          0.08302   
418       12.700         12.17           80.88      495.0          0.08785   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
211           0.06900         0.02669              0.01393         0.1533   
349           0.12060         0.01171              0.01787         0.2459   
302           0.18380         0.22830              0.12800         0.2249   
555           0.07658         0.05999              0.02738         0.1593   
525           0.07632         0.02565              0.01510         0.1678   
..                ...             ...                  ...            ...   
15            0.15950         0.16390              0.07364         0.2303   
347           0.07780         0.04608              0.03528         0.1521   
164           0.11450         0.13240              0.09702         0.1801   
374           0.06374         0.02556              0.02031         0.1872   
418           0.05794         0.02360              0.02402         0.1583   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
211                 0.06057  ...        13.300          24.99   
349                 0.06581  ...        12.810          17.72   
302                 0.07469  ...        23.680          29.43   
555                 0.06127  ...        10.840          34.91   
525                 0.07126  ...         9.473          18.45   
..                      ...  ...           ...            ...   
15                  0.07077  ...        17.460          37.13   
347                 0.05912  ...        17.270          17.93   
164                 0.05553  ...        28.010          28.22   
374                 0.05669  ...        14.840          20.21   
418                 0.06275  ...        13.650          16.92   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
211            85.22       546.3            0.1280             0.1880   
349            83.09       496.2            0.1293             0.1885   
302           158.80      1696.0            0.1347             0.3391   
555            69.57       357.6            0.1384             0.1710   
525            63.30       275.6            0.1641             0.2235   
..               ...         ...               ...                ...   
15            124.10       943.2            0.1678             0.6577   
347           114.20       880.8            0.1220             0.2009   
164           184.20      2403.0            0.1228             0.3583   
374            99.16       670.6            0.1105             0.2096   
418            88.12       566.9            0.1314             0.1607   

     concavity_worst  concave points_worst  symmetry_worst  \
211          0.14710               0.06913          0.2535   
349          0.03122               0.04766          0.3124   
302          0.49320               0.19230          0.3294   
555          0.20000               0.09127          0.2226   
525          0.17540               0.08512          0.2983   
..               ...                   ...             ...   
15           0.70260               0.17120         

In [254]:
y_train

211    B
349    B
302    M
555    B
525    B
      ..
15     M
347    B
164    M
374    B
418    B
Name: diagnosis, Length: 455, dtype: object

In [255]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [256]:
X_train

array([[-0.63911102, -0.02786613, -0.66632044, ..., -0.66069335,
        -0.59884503, -0.21046485],
       [-0.60750137, -0.96670833, -0.59475587, ..., -0.9886932 ,
         0.3757792 , -0.4351171 ],
       [ 1.73161234,  1.13271267,  1.79641604, ...,  1.22099003,
         0.65707992,  0.61233099],
       ...,
       [ 2.64541844,  0.70339287,  2.52038317, ...,  1.86721238,
         1.14521939,  0.45513016],
       [-0.10749427, -0.70487043, -0.15330235, ..., -0.64938827,
         0.70506651, -0.37324018],
       [-0.39198107, -1.62484143, -0.4428892 , ..., -0.46041025,
        -0.20171461,  0.60954374]])

In [257]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [258]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,

In [259]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [260]:
X_train_tensor.shape

torch.Size([455, 30])

In [261]:
y_train_tensor.shape

torch.Size([455])

In [262]:
from torch.utils.data import Dataset,DataLoader

class customedataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.lables=labels
    def __len__(self):
        return len(self.features)
    def __getitem__(self,idx):
        return self.features[idx],self.lables[idx]

In [263]:
train_datasets=customedataset(X_test_tensor,y_test_tensor)
test_datasets=customedataset(X_test_tensor,y_test_tensor)

In [264]:
train_datasets[10]

(tensor([ 1.3165, -0.3734,  1.2628,  1.3160,  0.6048,  0.3009,  0.4125,  0.9381,
          0.4084, -0.4626,  1.1817, -0.1321,  0.9977,  1.6456, -0.1625, -0.2100,
         -0.1682,  0.4185, -0.2012, -0.4471,  1.8296,  0.1654,  1.6873,  2.0259,
          1.0993,  0.4692,  0.4082,  1.3011,  0.9265, -0.1066]),
 tensor(1.))

In [265]:
train_loader=DataLoader(train_datasets,batch_size=32,shuffle=True)
test_loader=DataLoader(test_datasets,batch_size=32,shuffle=True)

In [266]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
    
  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [267]:
learning_rate = 0.1
epochs = 100

In [268]:
loss_function=nn.BCELoss()

In [269]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer 
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:
  # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))
    
    # zero gradients
    optimizer.zero_grad()
    
    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.9690574407577515
Epoch: 1, Loss: 0.7013992071151733
Epoch: 1, Loss: 0.5653990507125854
Epoch: 1, Loss: 0.422895222902298
Epoch: 2, Loss: 0.4092688262462616
Epoch: 2, Loss: 0.36652475595474243
Epoch: 2, Loss: 0.2714560925960541
Epoch: 2, Loss: 0.2592114508152008
Epoch: 3, Loss: 0.3213152289390564
Epoch: 3, Loss: 0.21154507994651794
Epoch: 3, Loss: 0.21064630150794983
Epoch: 3, Loss: 0.31366023421287537
Epoch: 4, Loss: 0.22942619025707245
Epoch: 4, Loss: 0.17254628241062164
Epoch: 4, Loss: 0.18551550805568695
Epoch: 4, Loss: 0.35372257232666016
Epoch: 5, Loss: 0.2389315962791443
Epoch: 5, Loss: 0.17870700359344482
Epoch: 5, Loss: 0.1982472985982895
Epoch: 5, Loss: 0.1542903184890747
Epoch: 6, Loss: 0.19411130249500275
Epoch: 6, Loss: 0.21473868191242218
Epoch: 6, Loss: 0.11687666177749634
Epoch: 6, Loss: 0.21600350737571716
Epoch: 7, Loss: 0.23455367982387543
Epoch: 7, Loss: 0.13575290143489838
Epoch: 7, Loss: 0.1677960902452469
Epoch: 7, Loss: 0.11487015336751938
Epoch

In [270]:
model.linear.bias

Parameter containing:
tensor([0.0695], requires_grad=True)

In [271]:
# model evaluation
accuracy_list=[]
with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)
  
#overall accuracy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'accuracy:{overall_accuracy:.4f}')

accuracy:0.9566
