In [43]:
import pandas as pd

df=pd.read_csv(r'C:\Users\abhin\Desktop\pytorch,deeplearning,nns\100_Unique_QA_Dataset.csv')
df.head()

question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [44]:
#tokenize
def tokenize(text):
    text=text.lower()
    text=text.replace('?','')
    text=text.replace("'",'')
    return text.split()


In [45]:
tokenize('what is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [46]:
vocab={'<UNK>':0} 

In [47]:
def build_vocab(row):
    print(row['question'],row['answer'])
    tokenize_question=tokenize(row['question'])
    tokenize_answer=tokenize(row['answer'])
    merged_tokens=tokenize_question+tokenize_answer
    print(merged_tokens)

    for token in merged_tokens:
        if token not in vocab:
            vocab[token]=len(vocab)
            


In [48]:
df.apply(build_vocab,axis=1)

What is the capital of France? Paris
['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
What is the capital of Germany? Berlin
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
Who wrote 'To Kill a Mockingbird'? Harper-Lee
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
What is the largest planet in our solar system? Jupiter
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
What is the boiling point of water in Celsius? 100
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
Who painted the Mona Lisa? Leonardo-da-Vinci
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
What is the square root of 64? 8
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
What is the chemical symbol for gold? Au
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
Which year did World War II end? 1945
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
What is the longe

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [49]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

In [50]:
len(vocab)

324

In [51]:
#covert words to numerical indices
def text_to_indices(text,vocab):
    indexed_text=[]

    for token in tokenize(text):
        if token in vocab:
            indexed_text.append(vocab[token])
        else:
            indexed_text.append(vocab['<UNK>'])
    return indexed_text

In [52]:
text_to_indices("what is the campusx", vocab)

[1, 2, 3, 0]

In [63]:
import torch
from torch.utils.data import Dataset,DataLoader

In [59]:
class qadataset(Dataset):
    def __init__(self,df,vocab):
        self.df=df
        self.vocab=vocab

    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self, index):
        numerical_que=text_to_indices(self.df.iloc[index]['question'],self.vocab)
        numerical_ans=text_to_indices(self.df.iloc[index]['answer'],self.vocab)
        return torch.tensor(numerical_que),torch.tensor(numerical_ans)

In [60]:
dataset=qadataset(df,vocab)

In [62]:

dataset[10]


(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [64]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [67]:
for question,answer in dataloader:
    print(question[0],answer[0])

tensor([10,  2,  3, 66,  5, 67]) tensor([68])
tensor([ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]) tensor([273])
tensor([ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]) tensor([145])
tensor([ 78,  79, 195,  81,  19,   3, 196, 197, 198]) tensor([199])
tensor([  1,   2,   3, 146, 147,  19, 148]) tensor([149])
tensor([ 1,  2,  3,  4,  5, 73]) tensor([74])
tensor([ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]) tensor([307])
tensor([ 42, 167,   2,   3,  17, 168, 169]) tensor([170])
tensor([42, 18,  2, 62, 63,  3, 64, 18]) tensor([65])
tensor([ 42, 107,   2, 108,  19, 109]) tensor([110])
tensor([  1,   2,   3, 122, 123,  19,   3,  45]) tensor([124])
tensor([ 1,  2,  3, 69,  5, 53]) tensor([260])
tensor([ 78,  79, 288,  81,  19,  14, 289]) tensor([85])
tensor([ 42, 290, 291, 118, 292, 158, 293, 294]) tensor([295])
tensor([  1,   2,   3,  69,   5, 155]) tensor([156])
tensor([ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]) tensor([179])
tensor([ 1,  2,  3, 33, 34,  5, 

In [68]:
import torch.nn as nn

In [69]:
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [73]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])


In [74]:
learning_rate = 0.001
epochs = 20

In [76]:
model = SimpleRNN(len(vocab))

In [77]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [78]:
# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 526.070142
Epoch: 2, Loss: 463.152794
Epoch: 3, Loss: 389.372210
Epoch: 4, Loss: 323.105013
Epoch: 5, Loss: 270.027112
Epoch: 6, Loss: 220.932496
Epoch: 7, Loss: 175.910485
Epoch: 8, Loss: 137.159123
Epoch: 9, Loss: 105.209724
Epoch: 10, Loss: 80.078041
Epoch: 11, Loss: 62.136461
Epoch: 12, Loss: 48.093975
Epoch: 13, Loss: 38.215131
Epoch: 14, Loss: 30.843662
Epoch: 15, Loss: 25.538247
Epoch: 16, Loss: 20.866137
Epoch: 17, Loss: 17.537963
Epoch: 18, Loss: 14.918850
Epoch: 19, Loss: 12.801680
Epoch: 20, Loss: 11.080018


In [79]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [80]:
predict(model, "What is the largest planet in our solar system?")

jupiter


In [ ]:
list(vocab.keys())[7]