In [201]:
import torch
print(torch.__version__)

2.5.1+cu121


In [202]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [203]:
import torch
print(torch.device("cpu"))  # Output: cpu
print(torch.cuda.is_available())  # Output: False


cpu
False


In [204]:
a=torch.empty(4,5)

In [205]:
type(a)

torch.Tensor

In [206]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [207]:
torch.rand(2,4)

tensor([[0.1371, 0.0177, 0.5417, 0.6575],
        [0.6141, 0.9619, 0.7244, 0.2700]])

In [208]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [209]:
torch.rand(2,4)

tensor([[0.1576, 0.8879, 0.9792, 0.2627],
        [0.1800, 0.6750, 0.1424, 0.3790]])

In [210]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [211]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

tensor shape

In [212]:
x=torch.tensor([[1,2,3],[4,5,7]])
x

tensor([[1, 2, 3],
        [4, 5, 7]])

In [213]:
x.shape

torch.Size([2, 3])

In [214]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [215]:
x.dtype

torch.int64

In [216]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 7.]])

In [217]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.5504, 0.9424, 0.3835],
        [0.6327, 0.5669, 0.3390]], dtype=torch.float64)

In [218]:
x

tensor([[1, 2, 3],
        [4, 5, 7]])

In [219]:
x+2

tensor([[3, 4, 5],
        [6, 7, 9]])

In [220]:
x-0.5

tensor([[0.5000, 1.5000, 2.5000],
        [3.5000, 4.5000, 6.5000]])

In [221]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 14]])

In [222]:
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.5000]])

In [223]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 49]])

In [224]:
a=torch.rand(2,3)

In [225]:
b=torch.rand(2,3)

In [226]:
a

tensor([[0.6150, 0.4967, 0.4521],
        [0.0575, 0.0687, 0.0501]])

In [227]:
b

tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])

In [228]:
a+b

tensor([[0.6257, 0.5311, 0.5733],
        [0.1065, 0.0997, 0.7693]])

In [229]:
b-a

tensor([[-0.6042, -0.4624, -0.3309],
        [-0.0085, -0.0377,  0.6691]])

In [230]:
x=torch.rand(2,3)

In [231]:
y=torch.rand(2,3)

In [232]:
x

tensor([[0.8067, 0.8379, 0.7694],
        [0.6694, 0.7203, 0.2235]])

In [233]:
y

tensor([[0.9502, 0.4655, 0.9314],
        [0.6533, 0.8914, 0.8988]])

In [234]:
x*y

tensor([[0.7665, 0.3900, 0.7166],
        [0.4373, 0.6420, 0.2009]])

In [235]:
x/y

tensor([[0.8490, 1.7998, 0.8260],
        [1.0247, 0.8081, 0.2486]])

In [236]:
torch.abs(x)

tensor([[0.8067, 0.8379, 0.7694],
        [0.6694, 0.7203, 0.2235]])

In [237]:
torch.neg(y)

tensor([[-0.9502, -0.4655, -0.9314],
        [-0.6533, -0.8914, -0.8988]])

In [238]:
torch.round(x)

tensor([[1., 1., 1.],
        [1., 1., 0.]])

In [239]:
torch.ceil(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [240]:
torch.floor(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [241]:
c=torch.tensor([[4,5,3],[6,7,8]])

In [242]:
torch.clamp(c,min=5,max=6)

tensor([[5, 5, 5],
        [6, 6, 6]])

In [243]:
d=torch.randint(size=(2,3),low=5,high=10,dtype=torch.float32)

In [244]:
d

tensor([[5., 7., 9.],
        [6., 6., 7.]])

In [245]:
torch.sum(d)

tensor(40.)

In [246]:
torch.sum(d,dim=0)

tensor([11., 13., 16.])

In [247]:
torch.sum(d,dim=1)

tensor([21., 19.])

In [248]:
torch.mean(d)

tensor(6.6667)

In [249]:
torch.mean(d,dim=1)

tensor([7.0000, 6.3333])

In [250]:
torch.median(d)

tensor(6.)

In [251]:
torch.max(d)

tensor(9.)

In [252]:
torch.min(d)

tensor(5.)

In [253]:
torch.prod(d,dim=1)

tensor([315., 252.])

In [254]:
torch.std(d)

tensor(1.3663)

In [255]:
torch.var(d)

tensor(1.8667)

In [256]:
torch.argmax(d)

tensor(2)

In [257]:
torch.argmin(d)

tensor(0)

In [258]:
d

tensor([[5., 7., 9.],
        [6., 6., 7.]])

In [259]:
torch.argsort(d)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [260]:
f=torch.randint(size=(2,3),low=3,high=6)
g=torch.randint(size=(3,2),low=3,high=6)

In [261]:
f

tensor([[5, 4, 5],
        [4, 5, 5]])

In [262]:
g

tensor([[3, 4],
        [5, 5],
        [3, 3]])

In [264]:
torch.matmul(f,g)

tensor([[50, 55],
        [52, 56]])

In [265]:
f 

tensor([[5, 4, 5],
        [4, 5, 5]])

In [268]:
torch.transpose(f,1,0)

tensor([[5, 4],
        [4, 5],
        [5, 5]])